# Generated by Django 5.0.3 on 2024-03-30 14:16

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('car_image_primary', models.ImageField(default='', upload_to=myapp.models.car_image_path)),
                ('car_image_secondary1', models.ImageField(blank=True, upload_to=myapp.models.car_image_path)),
                ('car_image_secondary2', models.ImageField(blank=True, upload_to=myapp.models.car_image_path)),
                ('locations', models.ManyToManyField(related_name='cars', to='myapp.location')),
            ],
        ),
    ]
